
import tkinter

win = tkinter.Tk(screenName=None, baseName=None,
                 className='Tk', useTk=True)

label = tkinter.Label(win, text='Taschenrechner')
label.pack(side=tkinter.TOP)

input_line = tkinter.Entry(win)
input_line.pack(side=tkinter.BOTTOM)
input_line.insert(tkinter.END,'2')
input_line.insert(tkinter.END,'*')
input_line.insert(tkinter.END,'2')
input_line.insert(tkinter.END,'=')
input_line.insert(tkinter.END,'4')

stack = tkinter.Text(win)
stack.pack(side=tkinter.BOTTOM)
stack.insert(tkinter.INSERT, "1\n2\n3\n")

row_1 = tkinter.Frame(win)
row_2 = tkinter.Frame(win)
row_3 = tkinter.Frame(win)
row_4 = tkinter.Frame(win)
row_5 = tkinter.Frame(win)
row_6 = tkinter.Frame(win)
row_7 = tkinter.Frame(win)

buttonlog = tkinter.Button(row_7, text='log')
buttonlog.pack(side=tkinter.LEFT)
buttonsin = tkinter.Button(row_7, text='sin')
buttonsin.pack(side=tkinter.LEFT)
buttoncos = tkinter.Button(row_7, text='cos')
buttoncos.pack(side=tkinter.LEFT)
buttontan = tkinter.Button(row_7, text='tan')
buttontan.pack(side=tkinter.LEFT)
buttonplus = tkinter.Button(row_3, text='+')
buttonplus.pack(side=tkinter.LEFT)
button0 = tkinter.Button(row_3, text='0')
button0.pack(side=tkinter.LEFT)
buttonminus = tkinter.Button(row_3, text='-')
buttonminus.pack(side=tkinter.LEFT)
button9 = tkinter.Button(row_6, text='9')
button9.pack(side=tkinter.LEFT)
button8 = tkinter.Button(row_6, text='8')
button8.pack(side=tkinter.LEFT)
button7 = tkinter.Button(row_6, text='7')
button7.pack(side=tkinter.LEFT)
button6 = tkinter.Button(row_5, text='6')
button6.pack(side=tkinter.LEFT)
button5 = tkinter.Button(row_5, text='5')
button5.pack(side=tkinter.LEFT)
button4 = tkinter.Button(row_5, text='4')
button4.pack(side=tkinter.LEFT)
button3 = tkinter.Button(row_4, text='3')
button3.pack(side=tkinter.LEFT)
button2 = tkinter.Button(row_4, text='2')
button2.pack(side=tkinter.LEFT)
button1 = tkinter.Button(row_4, text='1')
button1.pack(side=tkinter.LEFT)
buttonmal = tkinter.Button(row_2, text='*')
buttonmal.pack(side=tkinter.LEFT)
buttoncomma = tkinter.Button(row_2, text=',')
buttoncomma.pack(side=tkinter.LEFT)
buttondiv = tkinter.Button(row_2, text='/')
buttondiv.pack(side=tkinter.LEFT)
buttonistgl = tkinter.Button(row_1, text='=')
buttonistgl.pack(side=tkinter.LEFT)


row_1.pack(side=tkinter.BOTTOM)
row_2.pack(side=tkinter.BOTTOM)
row_3.pack(side=tkinter.BOTTOM)
row_4.pack(side=tkinter.BOTTOM)
row_5.pack(side=tkinter.BOTTOM)
row_6.pack(side=tkinter.BOTTOM)
row_7.pack(side=tkinter.BOTTOM)

win.mainloop()
